<?php

// ================= CONFIG =================

// Your upstream 3x-ui panels (subscription base URLs).
// The final upstream URL is: rtrim($base, '/') . '/' . rawurlencode($subKey)
$upstreams = array(
    "https://YOURDOMAIN.com:2096/subs/"
);

$timeout   = 8;
$cacheTTL  = 3600 * 4; // seconds (4 hours)
$rateLimit = 3;        // requests per window per IP
$rateWindow = 60;      // seconds

$cacheDir = __DIR__ . "/cache/";
$tmpDir   = __DIR__ . "/tmp/";

// Upstream TLS/HTTP options.
// Keep verify disabled if your upstream panel uses a self-signed/private certificate.
// For public valid certificates, set $verifyUpstreamTLS = true.
$verifyUpstreamTLS = false;
$upstreamHostHeader = ''; // empty = auto from upstream URL host
$upstreamPeerName   = ''; // empty = auto from upstream URL host
$outgoingUserAgent  = 'SubGateway/1.1';

// Profile filters. These preserve the old /tls, /ws and /grpc behavior,
// but make it easier to add more profile names later.
$configFilters = array(
    'tls'  => array('security' => 'tls'),
    'ws'   => array('type' => 'ws'),
    'grpc' => array('type' => 'grpc')
);

// ================= SAFE EXTRA FIELDS =================

// Admin-only extra query fields to inject into each exported config.
// Supported formats per profile:
//   'fp=chrome&sni=domain.com&alpn=h2,http/1.1&insecure=1'
// or:
//   array('fp' => 'chrome', 'sni' => 'domain.com', 'alpn' => 'h2,http/1.1', 'insecure' => '1')
//
// Use '*' for fields applied to every profile. Exact profile names override/extend '*'.
// Examples:
//   'ws'  => 'fp=chrome&sni=domain.com&alpn=h2,http/1.1&insecure=1',
//   'tls' => array('fp' => 'chrome', 'sni' => 'domain.com'),
$configExtraFields = array(
    '*'       => '',
    'default' => '',
    'tls'     => '',
    'ws'      => '',
    'grpc'    => ''
);

// false = do not overwrite fields already generated by 3x-ui.
// true  = admin extra fields replace existing same-name fields.
$overrideExistingExtraFields = false;

// Append " | profile" to the config remark/tag safely.
// For normal URI links this updates the #fragment. For vmess:// JSON links this updates ps.
$appendProfileNameToRemark = false;
$profileRemarkSeparator = ' | ';

// Extra field safety.
// Default false keeps future Xray/sing-box params usable while still validating key format.
// Set true if you want only the names below to be allowed.
$strictExtraFieldWhitelist = false;
$allowedExtraFieldNames = array(
    'type', 'security', 'encryption', 'flow',
    'sni', 'fp', 'alpn', 'insecure', 'allowInsecure',
    'host', 'path', 'headerType',
    'serviceName', 'mode', 'authority',
    'pbk', 'sid', 'spx',
    'seed', 'quicSecurity', 'key',
    'mux', 'ed', 'protocol', 'obfs', 'obfs-password'
);

// ================= OUTPUT MODE =================

$mode = isset($_GET['format']) ? strtolower((string)$_GET['format']) : 'auto';
// ?format=raw OR ?format=base64 OR ?format=auto

$userAgent = strtolower(isset($_SERVER['HTTP_USER_AGENT']) ? (string)$_SERVER['HTTP_USER_AGENT'] : '');
$badBots = array(
    'bot', 'crawler', 'spider', 'curl', 'wget', 'python',
    'scrapy', 'httpclient', 'go-http-client'
);

// ================= HELPERS =================

function detectMode($ua) {
    if (strpos($ua, 'clash') !== false) return 'base64';
    if (strpos($ua, 'v2rayn') !== false) return 'base64';
    if (strpos($ua, 'shadowrocket') !== false) return 'base64';
    if (strpos($ua, 'sing-box') !== false) return 'base64';
    if (strpos($ua, 'mozilla') !== false) return 'raw';
    return 'base64';
}

function sendPlainTextResponse($result) {
    header("Content-Type: text/plain; charset=utf-8");
    header("Cache-Control: no-store, no-cache, must-revalidate, max-age=0");
    header("Pragma: no-cache");
    header("Expires: 0");
    header("X-Robots-Tag: noindex, nofollow, noarchive, nosnippet, noimageindex");
    header("X-Content-Type-Options: nosniff");
    header("Referrer-Policy: no-referrer");
    header("X-Frame-Options: DENY");

    $etag = md5($result);
    header('ETag: "' . $etag . '"');

    if (isset($_SERVER['HTTP_IF_NONE_MATCH']) && trim($_SERVER['HTTP_IF_NONE_MATCH']) === '"' . $etag . '"') {
        http_response_code(304);
        exit;
    }

    echo $result;
    exit;
}

function ensureDirectory($dir) {
    if (!is_dir($dir)) {
        @mkdir($dir, 0755, true);
    }
    return is_dir($dir) && is_writable($dir);
}

function safeWriteFile($file, $data) {
    $dir = dirname($file);
    if (!is_dir($dir)) {
        @mkdir($dir, 0755, true);
    }

    $tmp = $file . '.tmp.' . getmypid() . '.' . mt_rand(1000, 999999);
    $ok = @file_put_contents($tmp, $data, LOCK_EX);
    if ($ok === false) {
        return false;
    }
    @chmod($tmp, 0644);

    if (!@rename($tmp, $file)) {
        @unlink($tmp);
        return false;
    }
    return true;
}

function splitPathSegments($path) {
    $path = trim((string)$path);
    $path = trim($path, "/ \t\n\r\0\x0B");
    if ($path === '') {
        return array();
    }

    $raw = explode('/', $path);
    $out = array();
    foreach ($raw as $seg) {
        $seg = trim($seg);
        if ($seg === '') continue;
        $out[] = rawurldecode($seg);
    }
    return $out;
}

function normalizeProfileName($name) {
    $name = strtolower(trim((string)$name));
    if ($name === '') return 'default';
    $name = preg_replace('/[^a-z0-9_-]/', '', $name);
    return $name === '' ? 'default' : $name;
}

function isBadBotUserAgent($ua, $badBots) {
    foreach ($badBots as $bot) {
        if ($bot !== '' && strpos($ua, $bot) !== false) {
            return true;
        }
    }
    return false;
}

function checkRateLimit($rateFile, $limit, $window) {
    if ($limit <= 0) return true;

    $now = time();
    $fh = @fopen($rateFile, 'c+');
    if (!$fh) {
        // Do not break subscriptions only because tmp is unavailable.
        return true;
    }

    $allowed = true;
    if (@flock($fh, LOCK_EX)) {
        rewind($fh);
        $raw = stream_get_contents($fh);
        $requests = json_decode($raw, true);
        if (!is_array($requests)) $requests = array();

        $clean = array();
        foreach ($requests as $t) {
            $t = (int)$t;
            if (($now - $t) < $window) {
                $clean[] = $t;
            }
        }

        if (count($clean) >= $limit) {
            $allowed = false;
        } else {
            $clean[] = $now;
            ftruncate($fh, 0);
            rewind($fh);
            fwrite($fh, json_encode(array_values($clean)));
            fflush($fh);
        }

        flock($fh, LOCK_UN);
    }

    fclose($fh);
    return $allowed;
}

function fetchSub($url, $timeout, $verifyTLS, $hostHeader, $peerName, $userAgent) {
    $urlHost = parse_url($url, PHP_URL_HOST);
    if ($urlHost === null || $urlHost === false || $urlHost === '') {
        return false;
    }

    $hostHeader = trim((string)$hostHeader);
    $peerName   = trim((string)$peerName);

    if ($hostHeader === '') $hostHeader = $urlHost;
    if ($peerName === '')   $peerName   = $urlHost;

    $headers = array(
        'Host: ' . $hostHeader,
        'User-Agent: ' . $userAgent,
        'Accept: text/plain, application/octet-stream, */*',
        'Connection: close'
    );

    $ctx = stream_context_create(array(
        'http' => array(
            'method' => 'GET',
            'header' => implode("\r\n", $headers) . "\r\n",
            'timeout' => $timeout,
            'ignore_errors' => true
        ),
        'ssl' => array(
            'verify_peer' => (bool)$verifyTLS,
            'verify_peer_name' => (bool)$verifyTLS,
            'peer_name' => $peerName,
            'SNI_enabled' => true,
            'SNI_server_name' => $peerName
        )
    ));

    return @file_get_contents($url, false, $ctx);
}

function base64Normalize($data) {
    $data = preg_replace('/\s+/', '', (string)$data);
    $data = strtr($data, '-_', '+/');
    $pad = strlen($data) % 4;
    if ($pad > 0) {
        $data .= str_repeat('=', 4 - $pad);
    }
    return $data;
}

function looksLikeSubscriptionText($text) {
    if (!is_string($text) || $text === '') return false;
    if (strpos($text, '://') !== false) return true;
    if (strpos($text, "\n") !== false && preg_match('/^[\x09\x0A\x0D\x20-\x7E]+$/', $text)) return true;
    return false;
}

function decodeSubscriptionPayload($data) {
    $trim = trim((string)$data);
    if ($trim === '') return '';

    $normalized = base64Normalize($trim);
    $decoded = base64_decode($normalized, true);
    if ($decoded !== false && looksLikeSubscriptionText($decoded)) {
        return $decoded;
    }

    $decoded = base64_decode($trim, true);
    if ($decoded !== false && looksLikeSubscriptionText($decoded)) {
        return $decoded;
    }

    return (string)$data;
}

function parseQueryPairs($query) {
    $pairs = array();
    $query = (string)$query;
    if ($query === '') return $pairs;

    $parts = explode('&', $query);
    foreach ($parts as $part) {
        if ($part === '') continue;
        $eq = strpos($part, '=');
        if ($eq === false) {
            $rawKey = $part;
            $rawVal = '';
            $hasEquals = false;
        } else {
            $rawKey = substr($part, 0, $eq);
            $rawVal = substr($part, $eq + 1);
            $hasEquals = true;
        }

        $pairs[] = array(
            'raw' => $part,
            'key' => rawurldecode($rawKey),
            'value' => rawurldecode($rawVal),
            'has_equals' => $hasEquals
        );
    }
    return $pairs;
}

function encodeQueryPair($key, $value) {
    return rawurlencode((string)$key) . '=' . rawurlencode((string)$value);
}

function getUriQuery($line) {
    $hashPos = strpos($line, '#');
    $beforeHash = ($hashPos === false) ? $line : substr($line, 0, $hashPos);
    $qPos = strpos($beforeHash, '?');
    if ($qPos === false) return '';
    return substr($beforeHash, $qPos + 1);
}

function getUriQueryParam($line, $name) {
    $pairs = parseQueryPairs(getUriQuery($line));
    $target = strtolower((string)$name);
    foreach ($pairs as $pair) {
        if (strtolower($pair['key']) === $target) {
            return $pair['value'];
        }
    }
    return null;
}

function matchConfigProfile($line, $configName, $configFilters) {
    if ($configName === 'default') return true;
    if (!isset($configFilters[$configName]) || !is_array($configFilters[$configName])) {
        // Unknown/custom profile names keep the old behavior: no filtering.
        return true;
    }

    foreach ($configFilters[$configName] as $key => $expected) {
        $actual = getUriQueryParam($line, $key);
        if ($actual !== null) {
            if (strtolower((string)$actual) !== strtolower((string)$expected)) {
                return false;
            }
            continue;
        }

        // Backward-compatible fallback for unusual links where parsing fails.
        if (strpos($line, $key . '=' . $expected) === false) {
            return false;
        }
    }

    return true;
}

function isSafeExtraFieldName($key, $allowedNames, $strictWhitelist) {
    $key = (string)$key;
    if ($key === '' || strlen($key) > 64) return false;
    if (!preg_match('/^[A-Za-z0-9_.:-]+$/', $key)) return false;

    if ($strictWhitelist) {
        foreach ($allowedNames as $allowed) {
            if (strtolower($allowed) === strtolower($key)) {
                return true;
            }
        }
        return false;
    }

    return true;
}

function isSafeExtraFieldValue($value) {
    $value = (string)$value;
    if (strlen($value) > 512) return false;
    // Reject control bytes. Query-breaking characters are encoded later, not rejected.
    return !preg_match('/[\x00-\x08\x0B\x0C\x0E-\x1F\x7F]/', $value);
}

function parseExtraFields($input, $allowedNames, $strictWhitelist) {
    $out = array();

    if (is_array($input)) {
        foreach ($input as $key => $value) {
            $key = trim((string)$key);
            if (is_bool($value)) $value = $value ? '1' : '0';
            if ($value === null) $value = '';
            $value = trim((string)$value);

            if (!isSafeExtraFieldName($key, $allowedNames, $strictWhitelist)) continue;
            if (!isSafeExtraFieldValue($value)) continue;
            $out[$key] = $value;
        }
        return $out;
    }

    $input = trim((string)$input);
    if ($input === '') return $out;
    if (isset($input[0]) && $input[0] === '?') {
        $input = substr($input, 1);
    }

    $parts = explode('&', $input);
    foreach ($parts as $part) {
        $part = trim($part);
        if ($part === '') continue;

        $eq = strpos($part, '=');
        if ($eq === false) {
            $key = rawurldecode($part);
            $value = '';
        } else {
            $key = rawurldecode(substr($part, 0, $eq));
            $value = rawurldecode(substr($part, $eq + 1));
        }

        $key = trim((string)$key);
        $value = trim((string)$value);

        if (!isSafeExtraFieldName($key, $allowedNames, $strictWhitelist)) continue;
        if (!isSafeExtraFieldValue($value)) continue;

        $out[$key] = $value;
    }

    return $out;
}

function getExtraFieldsForProfile($configName, $configExtraFields, $allowedNames, $strictWhitelist) {
    $fields = array();

    if (isset($configExtraFields['*'])) {
        $globalFields = parseExtraFields($configExtraFields['*'], $allowedNames, $strictWhitelist);
        foreach ($globalFields as $k => $v) $fields[$k] = $v;
    }

    if (isset($configExtraFields[$configName])) {
        $profileFields = parseExtraFields($configExtraFields[$configName], $allowedNames, $strictWhitelist);
        foreach ($profileFields as $k => $v) $fields[$k] = $v;
    }

    return $fields;
}

function applyExtraFieldsToUriLine($line, $extraFields, $overrideExisting) {
    if (empty($extraFields)) return $line;
    if (strpos($line, '://') === false) return $line;

    $hashPos = strpos($line, '#');
    if ($hashPos === false) {
        $beforeHash = $line;
        $fragment = null;
    } else {
        $beforeHash = substr($line, 0, $hashPos);
        $fragment = substr($line, $hashPos + 1);
    }

    $qPos = strpos($beforeHash, '?');
    if ($qPos === false) {
        $base = $beforeHash;
        $query = '';
    } else {
        $base = substr($beforeHash, 0, $qPos);
        $query = substr($beforeHash, $qPos + 1);
    }

    $pairs = parseQueryPairs($query);
    $existing = array();
    foreach ($pairs as $pair) {
        $existing[strtolower($pair['key'])] = true;
    }

    $keptRaw = array();
    foreach ($pairs as $pair) {
        $drop = false;
        if ($overrideExisting) {
            foreach ($extraFields as $k => $v) {
                if (strtolower($pair['key']) === strtolower($k)) {
                    $drop = true;
                    break;
                }
            }
        }
        if (!$drop) $keptRaw[] = $pair['raw'];
    }

    foreach ($extraFields as $key => $value) {
        $lower = strtolower($key);
        if (!$overrideExisting && isset($existing[$lower])) {
            continue;
        }
        $keptRaw[] = encodeQueryPair($key, $value);
    }

    $newQuery = implode('&', $keptRaw);
    $newLine = $base . ($newQuery !== '' ? '?' . $newQuery : '');
    if ($fragment !== null) {
        $newLine .= '#' . $fragment;
    }

    return $newLine;
}

function decodeVmessJson($payload) {
    $payload = base64Normalize($payload);
    $json = base64_decode($payload, true);
    if ($json === false) return null;
    $arr = json_decode($json, true);
    return is_array($arr) ? $arr : null;
}

function encodeVmessJson($arr) {
    if (defined('JSON_UNESCAPED_SLASHES') && defined('JSON_UNESCAPED_UNICODE')) {
        $json = json_encode($arr, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
    } else {
        $json = json_encode($arr);
    }
    if ($json === false) return false;
    return 'vmess://' . base64_encode($json);
}

function applyExtraFieldsToVmessLine($line, $extraFields, $overrideExisting) {
    if (stripos($line, 'vmess://') !== 0) return $line;
    if (empty($extraFields)) return $line;

    $payload = substr($line, 8);
    $hashPos = strpos($payload, '#');
    if ($hashPos !== false) {
        $payload = substr($payload, 0, $hashPos);
    }

    $arr = decodeVmessJson($payload);
    if (!is_array($arr)) return $line;

    foreach ($extraFields as $key => $value) {
        $vmessKey = $key;
        if (strtolower($key) === 'insecure') {
            $vmessKey = 'allowInsecure';
        }

        if (!$overrideExisting && array_key_exists($vmessKey, $arr) && (string)$arr[$vmessKey] !== '') {
            continue;
        }
        $arr[$vmessKey] = (string)$value;
    }

    $encoded = encodeVmessJson($arr);
    return $encoded === false ? $line : $encoded;
}

function appendProfileRemarkToVmessLine($line, $configName, $separator) {
    if (stripos($line, 'vmess://') !== 0) return $line;

    $payload = substr($line, 8);
    $arr = decodeVmessJson($payload);
    if (!is_array($arr)) return $line;

    $label = $separator . $configName;
    $ps = isset($arr['ps']) ? (string)$arr['ps'] : '';
    if ($ps === '' || strpos($ps, $label) === false) {
        $arr['ps'] = $ps . $label;
    }

    $encoded = encodeVmessJson($arr);
    return $encoded === false ? $line : $encoded;
}

function appendProfileRemarkToUriLine($line, $configName, $separator) {
    if ($configName === '') return $line;
    if (stripos($line, 'vmess://') === 0) {
        return appendProfileRemarkToVmessLine($line, $configName, $separator);
    }

    if (strpos($line, '://') === false) {
        return $line . rawurlencode($separator . $configName);
    }

    $labelRaw = $separator . $configName;
    $labelEncoded = rawurlencode($labelRaw);

    $hashPos = strpos($line, '#');
    if ($hashPos === false) {
        return $line . '#' . $labelEncoded;
    }

    $before = substr($line, 0, $hashPos + 1);
    $fragment = substr($line, $hashPos + 1);

    $decodedFragment = rawurldecode($fragment);
    if (strpos($decodedFragment, $labelRaw) !== false) {
        return $line;
    }

    return $before . $fragment . $labelEncoded;
}

function processConfigLine($line, $configName, $extraFields, $overrideExisting, $appendRemark, $remarkSeparator) {
    $line = trim($line);
    if ($line === '') return '';

    if (stripos($line, 'vmess://') === 0) {
        $line = applyExtraFieldsToVmessLine($line, $extraFields, $overrideExisting);
    } else {
        $line = applyExtraFieldsToUriLine($line, $extraFields, $overrideExisting);
    }

    if ($appendRemark) {
        $line = appendProfileRemarkToUriLine($line, $configName, $remarkSeparator);
    }

    return $line;
}

function extraFieldsSignature($fields) {
    if (!is_array($fields)) return '';
    ksort($fields);
    return sha1(json_encode($fields));
}

// ================= MAIN =================

if (isBadBotUserAgent($userAgent, $badBots)) {
    http_response_code(403);
    exit("Forbidden");
}

if ($mode !== 'auto' && $mode !== 'raw' && $mode !== 'base64') {
    $mode = 'auto';
}
if ($mode === 'auto') {
    $mode = detectMode($userAgent);
}

if (!ensureDirectory($cacheDir) || !ensureDirectory($tmpDir)) {
    http_response_code(500);
    exit("Cache/tmp directory is not writable");
}

$path = isset($_GET['path']) ? (string)$_GET['path'] : '';
if ($path === '' && isset($_SERVER['PATH_INFO'])) {
    $path = (string)$_SERVER['PATH_INFO'];
}

$segments = splitPathSegments($path);
if (empty($segments)) {
    http_response_code(400);
    exit("Bad request");
}

$subKey = end($segments);
$configName = count($segments) > 1 ? normalizeProfileName($segments[0]) : 'default';

$ip = isset($_SERVER['REMOTE_ADDR']) ? (string)$_SERVER['REMOTE_ADDR'] : 'unknown';
$rateFile = rtrim($tmpDir, '/\\') . DIRECTORY_SEPARATOR . md5($ip) . '.json';

if (!checkRateLimit($rateFile, $rateLimit, $rateWindow)) {
    http_response_code(429);
    exit("Too many requests, please wait moment");
}

$extraFields = getExtraFieldsForProfile(
    $configName,
    $configExtraFields,
    $allowedExtraFieldNames,
    $strictExtraFieldWhitelist
);

$cacheMaterial = array(
    'v' => 2,
    'sub' => $subKey,
    'profile' => $configName,
    'mode' => $mode,
    'extra' => extraFieldsSignature($extraFields),
    'override' => $overrideExistingExtraFields ? 1 : 0,
    'remark' => $appendProfileNameToRemark ? 1 : 0,
    'filters' => isset($configFilters[$configName]) ? $configFilters[$configName] : null
);
$cacheKey = sha1(json_encode($cacheMaterial));
$cacheFile = rtrim($cacheDir, '/\\') . DIRECTORY_SEPARATOR . $cacheKey . '.txt';

if (file_exists($cacheFile) && (time() - filemtime($cacheFile)) < $cacheTTL) {
    $cached = @file_get_contents($cacheFile);
    if ($cached !== false) {
        sendPlainTextResponse($cached);
    }
}

// ================= FETCH =================

$data = false;
foreach ($upstreams as $base) {
    $url = rtrim($base, '/') . '/' . rawurlencode($subKey);
    $fetched = fetchSub($url, $timeout, $verifyUpstreamTLS, $upstreamHostHeader, $upstreamPeerName, $outgoingUserAgent);

    if ($fetched !== false) {
        $data = $fetched;
        if (strlen($fetched) > 0) {
            break;
        }
    }
}

if ($data === false) {
    http_response_code(502);
    exit("All upstreams failed");
}

// ================= PROCESS =================

$decoded = decodeSubscriptionPayload($data);
$decoded = trim($decoded);
$lines = $decoded === '' ? array() : preg_split('/\r\n|\r|\n/', $decoded);
$output = array();

foreach ($lines as $line) {
    $line = trim((string)$line);
    if ($line === '') continue;

    if (!matchConfigProfile($line, $configName, $configFilters)) {
        continue;
    }

    $processed = processConfigLine(
        $line,
        $configName,
        $extraFields,
        $overrideExistingExtraFields,
        $appendProfileNameToRemark,
        $profileRemarkSeparator
    );

    if ($processed !== '') {
        $output[] = $processed;
    }
}

// ================= OUTPUT =================

$rawOutput = implode("\n", $output);
$result = ($mode === 'raw') ? $rawOutput : base64_encode($rawOutput);

// ================= STORE CACHE =================

safeWriteFile($cacheFile, $result);

sendPlainTextResponse($result);
